site_name: Felipe Valboeno PORRA - [MkDocs]

theme:
  name: material
  logo: assets/logo2.png
  palette:
    - scheme: default
      primary: custom
      accent: teal

  custom_dir: overrides
  features:
    - navigation.tabs

nav:
  - Home: index.md
  - Sobre mim: about.md


extra_css:
  - custom.css

markdown_extensions:
  - attr_list
